/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Neurync - Documentação da API
 * A API consiste na manipulação de registros do banco de dados de diferentes formas, além de métodos de login.
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateUserAlertMessage201,
  CreateUserAlertMessageBody,
  EditContentUserAlertMessageBody,
  GetUserAlertMessages200Item
} from '../../schemas';




  export const getAlertMessage = () => {
/**
 * Retorna todas as mensagens pre-salvas, que são direcionadas para o totem, de um usuário pelo o seu ID. Requer autenticação
 * @summary Retorna todas as mensagens sigilosas de um usuário
 */
const getUserAlertMessages = <TData = AxiosResponse<GetUserAlertMessages200Item[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/alert-messages/`,options
    );
  }
/**
 * Cria uma nova mensagem sigilosa pré-salva, através do ID de usuário e o conteúdo dela, deixando como padrão 'false' para o atributo 'is_favorited'. Requer autenticação
 * @summary Cria uma nova mensagem sigilosa pré-salva
 */
const createUserAlertMessage = <TData = AxiosResponse<CreateUserAlertMessage201>>(
    createUserAlertMessageBody: CreateUserAlertMessageBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/alert-messages/`,
      createUserAlertMessageBody,options
    );
  }
/**
 * Edita o conteúdo de uma mensagem pré-salva de um usuário, buscando pelo o ID dessa mensagem. Requer autenticação
 * @summary Edita o conteúdo de uma mensagem pré-salva de um usuário.
 */
const editContentUserAlertMessage = <TData = AxiosResponse<unknown>>(
    id: string,
    editContentUserAlertMessageBody: EditContentUserAlertMessageBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/alert-messages/edit/content/${id}`,
      editContentUserAlertMessageBody,options
    );
  }
/**
 * Favorita uma mensagem sigilosa pré-salva do usuário. Requer autenticação
 * @summary Favorita uma mensagem sigilosa pré-salva do usuário.
 */
const favoriteContentUserAlertMessage = <TData = AxiosResponse<unknown>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/alert-messages/favorite/${id}`,undefined,options
    );
  }
/**
 * Desfavorita uma mensagem sigilosa pré-salva do usuário. Requer autenticação
 * @summary Desfavorita uma mensagem sigilosa pré-salva do usuário.
 */
const unfavoriteContentUserAlertMessage = <TData = AxiosResponse<unknown>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/alert-messages/unfavorite/${id}`,undefined,options
    );
  }
/**
 * Deleta uma mensagem sigilosa pré-salva do usuário. Requer autenticação
 * @summary Deleta uma mensagem sigilosa pré-salva do usuário.
 */
const deleteContentUserAlertMessage = <TData = AxiosResponse<unknown>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/alert-messages/${id}`,options
    );
  }
return {getUserAlertMessages,createUserAlertMessage,editContentUserAlertMessage,favoriteContentUserAlertMessage,unfavoriteContentUserAlertMessage,deleteContentUserAlertMessage}};
export type GetUserAlertMessagesResult = AxiosResponse<GetUserAlertMessages200Item[]>
export type CreateUserAlertMessageResult = AxiosResponse<CreateUserAlertMessage201>
export type EditContentUserAlertMessageResult = AxiosResponse<unknown>
export type FavoriteContentUserAlertMessageResult = AxiosResponse<unknown>
export type UnfavoriteContentUserAlertMessageResult = AxiosResponse<unknown>
export type DeleteContentUserAlertMessageResult = AxiosResponse<unknown>
