/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Neurync - Documentação da API
 * A API consiste na manipulação de registros do banco de dados de diferentes formas, além de métodos de login.
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateUserHelp201,
  CreateUserHelpBody,
  EditUserHelpBody,
  GetUserHelps200Item
} from '../../schemas';




  export const getHelps = () => {
/**
 * Retorna todas as formas de ajua de crise de um usuário, através de seu ID
 * @summary Retorna os 'helps' de um usuário
 */
const getUserHelps = <TData = AxiosResponse<GetUserHelps200Item[]>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/helps/${userId}`,options
    );
  }
/**
 * Cria uma ajuda de crise do usuário. Requer autenticação
 * @summary Criar um 'help' de um usuário
 */
const createUserHelp = <TData = AxiosResponse<CreateUserHelp201>>(
    createUserHelpBody: CreateUserHelpBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/helps/`,
      createUserHelpBody,options
    );
  }
/**
 * Edita uma ajuda de crise do usuário. Requer autenticação
 * @summary Edita um 'help' de um usuário
 */
const editUserHelp = <TData = AxiosResponse<unknown>>(
    id: string,
    editUserHelpBody: EditUserHelpBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/helps/${id}`,
      editUserHelpBody,options
    );
  }
/**
 * Deleta uma ajuda de crise do usuário. Requer autenticação
 * @summary Deleta um 'help' de um usuário
 */
const deleteUserHelp = <TData = AxiosResponse<unknown>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/helps/${id}`,options
    );
  }
return {getUserHelps,createUserHelp,editUserHelp,deleteUserHelp}};
export type GetUserHelpsResult = AxiosResponse<GetUserHelps200Item[]>
export type CreateUserHelpResult = AxiosResponse<CreateUserHelp201>
export type EditUserHelpResult = AxiosResponse<unknown>
export type DeleteUserHelpResult = AxiosResponse<unknown>
