/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Neurync - Documentação da API
 * A API consiste na manipulação de registros do banco de dados de diferentes formas, além de métodos de login.
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateUserDanger201,
  CreateUserDangerBody,
  EditUserDangerBody,
  GetUserDangers200Item
} from '../../schemas';




  export const getDangers = () => {
/**
 * Retorna todos os gatilhos de crise de um usuário, através de seu ID
 * @summary Retorna os 'dangers' de um usuário
 */
const getUserDangers = <TData = AxiosResponse<GetUserDangers200Item[]>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/dangers/${userId}`,options
    );
  }
/**
 * Cria um gatilho de crise do usuário. Requer autenticação
 * @summary Criar um 'danger' de um usuário
 */
const createUserDanger = <TData = AxiosResponse<CreateUserDanger201>>(
    createUserDangerBody: CreateUserDangerBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/dangers/`,
      createUserDangerBody,options
    );
  }
/**
 * Edita um gatilho de crise do usuário. Requer autenticação
 * @summary Edita um 'danger' de um usuário
 */
const editUserDanger = <TData = AxiosResponse<unknown>>(
    id: string,
    editUserDangerBody: EditUserDangerBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/dangers/${id}`,
      editUserDangerBody,options
    );
  }
/**
 * Deleta um gatilho de crise do usuário. Requer autenticação
 * @summary Deleta um 'danger' de um usuário
 */
const deleteUserDanger = <TData = AxiosResponse<unknown>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/dangers/${id}`,options
    );
  }
return {getUserDangers,createUserDanger,editUserDanger,deleteUserDanger}};
export type GetUserDangersResult = AxiosResponse<GetUserDangers200Item[]>
export type CreateUserDangerResult = AxiosResponse<CreateUserDanger201>
export type EditUserDangerResult = AxiosResponse<unknown>
export type DeleteUserDangerResult = AxiosResponse<unknown>
