/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Neurync - Documentação da API
 * A API consiste na manipulação de registros do banco de dados de diferentes formas, além de métodos de login.
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateUserNonverbalMessage201,
  CreateUserNonverbalMessageBody,
  EditUserNonverbalMessageBody,
  GetUserNonverbalMessages200Item
} from '../../schemas';




  export const getNonverbalMessage = () => {
/**
 * Retorna todas as mensagens não verbais pré-prontas de um usuário, com base no ID. Requer autenticação.
 * @summary Listar mensagens não verbais de um usuário
 */
const getUserNonverbalMessages = <TData = AxiosResponse<GetUserNonverbalMessages200Item[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://192.168.2.101:3333/nonverbal-messages/`,options
    );
  }
/**
 * Cria uma nova mensagem não verbal pré-pronta para o usuário autenticado.
 * @summary Criar mensagem não verbal
 */
const createUserNonverbalMessage = <TData = AxiosResponse<CreateUserNonverbalMessage201>>(
    createUserNonverbalMessageBody: CreateUserNonverbalMessageBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://192.168.2.101:3333/nonverbal-messages/`,
      createUserNonverbalMessageBody,options
    );
  }
/**
 * Edita uma mensagem não verbal existente de um usuário autenticado.
 * @summary Editar mensagem não verbal
 */
const editUserNonverbalMessage = <TData = AxiosResponse<unknown>>(
    id: string,
    editUserNonverbalMessageBody: EditUserNonverbalMessageBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://192.168.2.101:3333/nonverbal-messages/edit/${id}`,
      editUserNonverbalMessageBody,options
    );
  }
/**
 * Marca uma mensagem não verbal como favorita.
 * @summary Favoritar mensagem não verbal
 */
const favoriteUserNonverbalMessage = <TData = AxiosResponse<unknown>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://192.168.2.101:3333/nonverbal-messages/favorite/${id}`,undefined,options
    );
  }
/**
 * Remove a marcação de favorita de uma mensagem não verbal.
 * @summary Desfavoritar mensagem não verbal
 */
const unfavoriteUserNonverbalMessage = <TData = AxiosResponse<unknown>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://192.168.2.101:3333/nonverbal-messages/unfavorite/${id}`,undefined,options
    );
  }
/**
 * Deleta uma mensagem não verbal do usuário.
 * @summary Deletar mensagem não verbal
 */
const deleteUserNonverbalMessage = <TData = AxiosResponse<unknown>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://192.168.2.101:3333/nonverbal-messages/${id}`,options
    );
  }
return {getUserNonverbalMessages,createUserNonverbalMessage,editUserNonverbalMessage,favoriteUserNonverbalMessage,unfavoriteUserNonverbalMessage,deleteUserNonverbalMessage}};
export type GetUserNonverbalMessagesResult = AxiosResponse<GetUserNonverbalMessages200Item[]>
export type CreateUserNonverbalMessageResult = AxiosResponse<CreateUserNonverbalMessage201>
export type EditUserNonverbalMessageResult = AxiosResponse<unknown>
export type FavoriteUserNonverbalMessageResult = AxiosResponse<unknown>
export type UnfavoriteUserNonverbalMessageResult = AxiosResponse<unknown>
export type DeleteUserNonverbalMessageResult = AxiosResponse<unknown>
