/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Neurync - Documentação da API
 * A API consiste na manipulação de registros do banco de dados de diferentes formas, além de métodos de login.
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateUser201,
  CreateUserBody,
  EditUserAboutBody,
  EditUserBody,
  EditUserNeurodivergenceBody,
  GetUserById200,
  LoginUser200,
  LoginUserBody
} from '../../schemas';




  export const getUsers = () => {
/**
 * Retorna as informações de um usuário, com determinado ID, como resposta
 * @summary Retorna as informações de um usuário
 */
const getUserById = <TData = AxiosResponse<GetUserById200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://192.168.2.101:3333/users/${id}`,options
    );
  }
/**
 * Edita os dados de um usuário com seu ID como parâmetro.
 * @summary Edita os dados de um usuário
 */
const editUser = <TData = AxiosResponse<unknown>>(
    id: string,
    editUserBody: EditUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://192.168.2.101:3333/users/${id}`,
      editUserBody,options
    );
  }
/**
 * Deleta os dados de um usuário com seu ID como parâmetro.
 * @summary Deleta os dados de um usuário
 */
const deleteUser = <TData = AxiosResponse<unknown>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://192.168.2.101:3333/users/${id}`,options
    );
  }
/**
 * Cria um usuário no banco de dados, pegando nome, email e senha, encriptando esta última.
 * @summary Cria um usuário no BD
 */
const createUser = <TData = AxiosResponse<CreateUser201>>(
    createUserBody: CreateUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://192.168.2.101:3333/users/register`,
      createUserBody,options
    );
  }
/**
 * Realiza um login com base em email e senha do usuário, retornando um JWT Token.
 * @summary Faz login do usuário
 */
const loginUser = <TData = AxiosResponse<LoginUser200>>(
    loginUserBody: LoginUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://192.168.2.101:3333/users/login`,
      loginUserBody,options
    );
  }
/**
 * Edita o 'about' (sobre) de um usuário.
 * @summary Edita o 'about' de um usuário.
 */
const editUserAbout = <TData = AxiosResponse<unknown>>(
    editUserAboutBody: EditUserAboutBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://192.168.2.101:3333/users/about`,
      editUserAboutBody,options
    );
  }
/**
 * Edita o 'neurodivergence' (neurodivergencia) de um usuário.
 * @summary Edita o 'neurodivergence' de um usuário.
 */
const editUserNeurodivergence = <TData = AxiosResponse<unknown>>(
    editUserNeurodivergenceBody: EditUserNeurodivergenceBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://192.168.2.101:3333/users/neurodivergence`,
      editUserNeurodivergenceBody,options
    );
  }
return {getUserById,editUser,deleteUser,createUser,loginUser,editUserAbout,editUserNeurodivergence}};
export type GetUserByIdResult = AxiosResponse<GetUserById200>
export type EditUserResult = AxiosResponse<unknown>
export type DeleteUserResult = AxiosResponse<unknown>
export type CreateUserResult = AxiosResponse<CreateUser201>
export type LoginUserResult = AxiosResponse<LoginUser200>
export type EditUserAboutResult = AxiosResponse<unknown>
export type EditUserNeurodivergenceResult = AxiosResponse<unknown>
