/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Neurync - Documentação da API
 * A API consiste na manipulação de registros do banco de dados de diferentes formas, além de métodos de login.
 * OpenAPI spec version: 1.0.0
 */

export type CreateUserHelp201Message = typeof CreateUserHelp201Message[keyof typeof CreateUserHelp201Message];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserHelp201Message = {
  Help_created: 'Help created',
} as const;
