/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Neurync - Documentação da API
 * A API consiste na manipulação de registros do banco de dados de diferentes formas, além de métodos de login.
 * OpenAPI spec version: 1.0.0
 */

export type CreateUserNonverbalMessage201Message = typeof CreateUserNonverbalMessage201Message[keyof typeof CreateUserNonverbalMessage201Message];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserNonverbalMessage201Message = {
  Nonverbal_Message_created: 'Nonverbal Message created',
} as const;
