/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Neurync - Documentação da API
 * A API consiste na manipulação de registros do banco de dados de diferentes formas, além de métodos de login.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateUserNonverbalMessage201Message } from './createUserNonverbalMessage201Message';

export type CreateUserNonverbalMessage201 = {
  message: CreateUserNonverbalMessage201Message;
};
