/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Neurync - Documentação da API
 * A API consiste na manipulação de registros do banco de dados de diferentes formas, além de métodos de login.
 * OpenAPI spec version: 1.0.0
 */
import type { EditUserNonverbalMessageBodyType } from './editUserNonverbalMessageBodyType';

export type EditUserNonverbalMessageBody = {
  content: string;
  emoji_icon: string;
  type: EditUserNonverbalMessageBodyType;
  is_favorited: boolean;
};
