/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Neurync - Documentação da API
 * A API consiste na manipulação de registros do banco de dados de diferentes formas, além de métodos de login.
 * OpenAPI spec version: 1.0.0
 */

export type GetUserNonverbalMessages200ItemType = typeof GetUserNonverbalMessages200ItemType[keyof typeof GetUserNonverbalMessages200ItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserNonverbalMessages200ItemType = {
  feelings: 'feelings',
  problems: 'problems',
} as const;
